export interface Product {
  id: string;
  slug: string;
  name: string;
  category: string;
  description: string;
  shortDescription: string;
  image: string;
  secondaryImages?: string[];
  price?: string;
  priceLabel?: string;
  features: string[];
  materials?: string[];
  isNew?: boolean;
  isFeatured?: boolean;
  isSeasonal?: boolean;
  availability: 'available' | 'made-to-order' | 'limited' | 'sold-out';
  tags: string[];
}

export const categories = [
  'Todos',
  'Muñecas',
  'Tarjetas',
  'Papelería',
  'Manualidades Recicladas',
  'Personalizados',
];

export const products: Product[] = [
  {
    id: 'prod-1',
    slug: 'fofucha-ciclista-aventura-1',
    name: 'Muñeca Fofucha Ciclista de Aventura',
    category: 'Muñecas',
    description: 'Fofucha artesanal modelada en goma eva que representa a una ciclista lista para la aventura. Incluye bicicleta personalizada a escala, casco protector aerodinámico con visera tornasolada, medalla al cuello y vestimenta deportiva detallada.',
    shortDescription: 'Fofucha ciclista con bicicleta a escala, casco y medalla.',
    image: '/images/img/is1.jpg',
    secondaryImages: ['/images/img/is3.jpg', '/images/img/is5.jpg'],
    price: '$48.000',
    priceLabel: 'Pieza artesanal',
    features: ['Bicicleta artesanal a escala', 'Casco y gafas tornasoladas', 'Medalla metálica', 'Colores personalizables'],
    materials: ['Goma eva termoformada', 'Pintura acrílica', 'Accesorios metálicos'],
    isFeatured: true,
    availability: 'available',
    tags: ['muñeca', 'fofucha', 'ciclista', 'deporte', 'bicicleta'],
  },
  {
    id: 'prod-3',
    slug: 'fofucha-ciclista-taller-3',
    name: 'Fofucha Ciclista en Taller',
    category: 'Muñecas',
    description: 'Muñeca fofucha ciclista terminada en mesa de taller con acabados de alta definición y detalles en relieve.',
    shortDescription: 'Fofucha ciclista con vestimenta completa y bicicleta.',
    image: '/images/img/is3.jpg',
    secondaryImages: ['/images/img/is1.jpg', '/images/img/is5.jpg'],
    price: '$48.000',
    priceLabel: 'Edición taller',
    features: ['Bicicleta celeste a escala', 'Gafas con reflejo', 'Ropa deportiva en capas'],
    materials: ['Goma eva de alta densidad', 'Pintura satinada'],
    availability: 'available',
    tags: ['muñeca', 'fofucha', 'ciclista'],
  },
  {
    id: 'prod-5',
    slug: 'fofucha-ciclista-detalle-5',
    name: 'Fofucha Ciclista - Vista de Detalles',
    category: 'Muñecas',
    description: 'Perspectiva detallada de la fofucha ciclista mostrando el trabajo de textura en casco, cabello y vestimenta.',
    shortDescription: 'Detalle de modelado en fofucha ciclista.',
    image: '/images/img/is5.jpg',
    secondaryImages: ['/images/img/is1.jpg', '/images/img/is3.jpg'],
    price: '$48.000',
    priceLabel: 'Consultar',
    features: ['Modelado 3D preciso', 'Zapatos deportivos en goma eva', 'Medalla al mérito'],
    materials: ['Goma eva', 'Pinturas acrílicas'],
    availability: 'available',
    tags: ['muñeca', 'fofucha', 'detalle'],
  },
  {
    id: 'prod-6',
    slug: 'muneco-pijama-conejito-mascota-6',
    name: 'Muñeco Pijama de Conejito con Cachorro',
    category: 'Muñecas',
    description: 'Tierno muñeco artesanal con enterizo pijama de conejito celeste con capucha ondeada, bordado de zanahoria y su cachorrito fiel en brazos.',
    shortDescription: 'Muñeco pijama de conejo con perrito compañero.',
    image: '/images/img/is6.jpg',
    secondaryImages: [],
    price: '$42.000',
    priceLabel: 'Unidad con empaque',
    features: ['Capucha ondulada', 'Perrito desmontable', 'Empaque protector artesanal'],
    materials: ['Goma eva toalla', 'Pinturas al agua'],
    isNew: true,
    availability: 'available',
    tags: ['muñeco', 'pijama', 'conejo', 'infantil'],
  },
  {
    id: 'prod-7',
    slug: 'tarjeta-aliento-life-is-a-precious-gift-7',
    name: 'Tarjeta de Aliento "Life is a Precious Gift"',
    category: 'Tarjetas',
    description: 'Hermosa tarjeta artesanal negra con mensajes de motivación en letras doradas y relieve ("Life is a precious gift", "Make Progress", "Get Well Soon").',
    shortDescription: 'Tarjeta elegante negra con dorados y frase motivacional.',
    image: '/images/img/is7.jpg',
    secondaryImages: ['/images/img/is11.jpg', '/images/img/is20.jpg'],
    price: '$15.000',
    priceLabel: 'Unidad con sobre',
    features: ['Letras en relieve dorado', 'Diseño de aliento y recuperación', 'Incluye sobre de protección'],
    materials: ['Cartulina de alto gramaje', 'Papel foil dorado'],
    isFeatured: true,
    availability: 'available',
    tags: ['tarjeta', 'motivacion', 'dorado', 'regalo'],
  },
  {
    id: 'prod-8',
    slug: 'fofucha-boho-chic-trenzas-8',
    name: 'Muñeca Fofucha Boho Chic con Trenzas',
    category: 'Muñecas',
    description: 'Muñeca fofucha estilo bohemio con pañuelo naranja en la cabeza, trenzas rubias artesanales, top con flor bordada y pantalón acampanado con flecos y apliques florales.',
    shortDescription: 'Fofucha estilo boho chic con trenzas, pañuelo y pantalón acampanado.',
    image: '/images/img/is8.jpg',
    secondaryImages: ['/images/img/is10.jpg', '/images/img/is12.jpg'],
    price: '$52.000',
    priceLabel: 'Edición artesanal',
    features: ['Trenzas tejidas a mano', 'Pantalón acampanado con flecos', 'Pañuelo estampado', 'Flores 3D'],
    materials: ['Goma eva texturada', 'Encaje artesanal', 'Pintura satinada'],
    isNew: true,
    isFeatured: true,
    availability: 'available',
    tags: ['muñeca', 'fofucha', 'boho', 'hippie', 'primavera'],
  },
  {
    id: 'prod-9',
    slug: 'libreta-diario-muneca-relieve-9',
    name: 'Libreta Diario con Muñeca en Relieve',
    category: 'Papelería',
    description: 'Cuaderno anillado con tapa dura texturada en tonos plateados, decorada con una muñeca artesanal de goma eva con vestido blanco, lazo rojo y reloj solar.',
    shortDescription: 'Libreta anillada con muñeca en relieve en la portada.',
    image: '/images/img/is9.jpg',
    secondaryImages: [],
    price: '$24.000',
    priceLabel: 'Unidad',
    features: ['Muñeca 3D en la portada', 'Tapa dura forrada y texturada', '80 hojas de 90g', 'Anillado reinforced'],
    materials: ['Goma eva', 'Cartón prensado', 'Papel ecológico', 'Cristales decorativos'],
    isFeatured: true,
    availability: 'available',
    tags: ['libreta', 'cuaderno', 'papeleria', 'muñeca', 'diario'],
  },
  {
    id: 'prod-10',
    slug: 'fofucha-detalles-trenzado-10',
    name: 'Fofucha Boho - Vista de Trenzado',
    category: 'Muñecas',
    description: 'Perspectiva detallada del peinado con trenzas dobles, cinta artesanal y vestuario primaveral de la fofucha boho.',
    shortDescription: 'Detalle de peinado y vestuario en fofucha boho.',
    image: '/images/img/is10.jpg',
    secondaryImages: ['/images/img/is8.jpg', '/images/img/is12.jpg'],
    price: '$50.000',
    priceLabel: 'Unidad',
    features: ['Peinado con trenzas dobles', 'Detalles en encaje', 'Base de apoyo estable'],
    materials: ['Goma eva termoformada', 'Encajes'],
    availability: 'available',
    tags: ['muñeca', 'fofucha', 'artesanal'],
  },
  {
    id: 'prod-11',
    slug: 'tarjeta-motivacional-life-full-of-colors-11',
    name: 'Tarjeta Motivacional "Life Full of Colors"',
    category: 'Tarjetas',
    description: 'Tarjeta moderna y vibrante con fondo verde manzana, motivo a cuadros en diagonal, gemas brillantes en relieve y mensajes inspiradores transparentes.',
    shortDescription: 'Tarjeta con cristales brillantes y mensaje motivacional.',
    image: '/images/img/is11.jpg',
    secondaryImages: ['/images/img/is7.jpg', '/images/img/is20.jpg'],
    price: '$11.000',
    priceLabel: 'Unidad con sobre',
    features: ['Mensajes en relieve', 'Gemas y cristales aplicados a mano', 'Contraste de color vibrante', 'Sobre artesanal incluido'],
    materials: ['Cartulina texturada 240g', 'Gemas acrílicas', 'Acetato impreso'],
    isFeatured: true,
    availability: 'available',
    tags: ['tarjeta', 'motivacional', 'color', 'regalo'],
  },
  {
    id: 'prod-12',
    slug: 'fofucha-pantalon-acampanado-12',
    name: 'Fofucha Boho - Detalle Pantalón Bordado',
    category: 'Muñecas',
    description: 'Vista detallada de la muñeca artesanal con pantalón acampanado azul jeans con bordados florales en 3D, flecos inferiores y cinturón de cordel.',
    shortDescription: 'Detalle de pantalón acampanado y flores en relieve.',
    image: '/images/img/is12.jpg',
    secondaryImages: ['/images/img/is8.jpg', '/images/img/is10.jpg'],
    price: '$52.000',
    priceLabel: 'Unidad',
    features: ['Flores modeladas en miniatura', 'Pantalón acampanado texturado', 'Cinturón artesanal'],
    materials: ['Goma eva', 'Pinturas acrílicas', 'Cordel'],
    availability: 'available',
    tags: ['muñeca', 'fofucha', 'vintage'],
  },
  {
    id: 'prod-13',
    slug: 'osita-bebe-tierna-goma-eva-13',
    name: 'Osita Bebé Tierna en Goma Eva',
    category: 'Muñecas',
    description: 'Tierna figura de osita bebé acostada sobre su mantita rosa, con chupete, moño decorativo y corazón en la espalda. Ideal para baby shower o souvenirs de nacimiento.',
    shortDescription: 'Tierna osita bebé con chupete y mantita para cuarto infantil o baby shower.',
    image: '/images/img/is13.jpg',
    secondaryImages: ['/images/img/is14.jpg', '/images/img/is15.jpg'],
    price: '$28.000',
    priceLabel: 'Unidad',
    features: ['Modelado 3D suave', 'Chupete y moño en relieve', 'Mantita texturada'],
    materials: ['Goma eva glitter y lisa', 'Pigmentos al pastel'],
    isSeasonal: true,
    isFeatured: true,
    availability: 'available',
    tags: ['bebe', 'osito', 'nacimiento', 'baby-shower', 'muñeca'],
  },
  {
    id: 'prod-14',
    slug: 'osita-bebe-lateral-14',
    name: 'Osita Bebé con Moño y Chupete (Vista Lateral)',
    category: 'Muñecas',
    description: 'Vista lateral de la osita bebé mostrando la curva de modelado del cuerpo, las orejitas y la mantita texturada.',
    shortDescription: 'Detalle de modelado en figura de osita bebé.',
    image: '/images/img/is14.jpg',
    secondaryImages: ['/images/img/is13.jpg', '/images/img/is15.jpg'],
    price: '$28.000',
    priceLabel: 'Unidad',
    features: ['Acabado con suave brillo glitter', 'Pestañas pintadas a mano', 'Tamaño compacto para repisa'],
    materials: ['Goma eva', 'Pinturas especiales'],
    availability: 'available',
    tags: ['bebe', 'osito', 'figura', 'muñeca'],
  },
  {
    id: 'prod-15',
    slug: 'osita-bebe-corazon-15',
    name: 'Osita Bebé con Detalle de Corazón',
    category: 'Muñecas',
    description: 'Figura de osita bebé con corazón rosa en relieve, ideal para recuerdos de bautismo o nacimientos.',
    shortDescription: 'Osita bebé artesanal con corazón rosa en relieve.',
    image: '/images/img/is15.jpg',
    secondaryImages: ['/images/img/is13.jpg', '/images/img/is14.jpg'],
    price: '$28.000',
    priceLabel: 'Unidad',
    features: ['Corazón en relieve', 'Textura aterciopelada', 'Ideal para souvenirs'],
    materials: ['Goma eva', 'Pinturas acrílicas'],
    availability: 'available',
    tags: ['bebe', 'osito', 'souvenir', 'muñeca'],
  },
  {
    id: 'prod-16',
    slug: 'cesta-organizadora-textil-flores-azules-16',
    name: 'Cesta Organizadora Textil con Flores Azules',
    category: 'Manualidades Recicladas',
    description: 'Cesta organizadora artesanal fabricada con base reciclada reforzada, forrada en tela rústica de lino y lienzo con flores botánicas azules, terminada con cordón de yute perimetral y flores de goma eva en relieve.',
    shortDescription: 'Cesta organizadora ecológica con lino, flores azules y cordón de yute.',
    image: '/images/img/is16.jpg',
    secondaryImages: [],
    price: '$26.000',
    priceLabel: 'Unidad',
    features: ['Estructura reciclada y reforzada', 'Forro textil desmontable', 'Flores de goma eva esculpidas', 'Cordón de yute'],
    materials: ['Cartón reciclado', 'Tela de lino y algodón', 'Goma eva', 'Yute natural'],
    isFeatured: true,
    availability: 'available',
    tags: ['reciclado', 'cesta', 'organizador', 'hogar', 'sostenible'],
  },
  {
    id: 'prod-17',
    name: 'Pareja de Fofuchos con Perrito',
    slug: 'pareja-fofuchos-con-perrito-17',
    category: 'Muñecas',
    description: 'Set de muñecos fofuchos personalizados compuesto por niña con enterizo rojo y niño en camiseta sosteniendo a su mascota en correa.',
    shortDescription: 'Pareja de fofuchos artesanales con su cachorrito.',
    image: '/images/img/is17.jpg',
    secondaryImages: [],
    price: '$55.000',
    priceLabel: 'Set completo',
    features: ['Pareja de personajes', 'Incluye mascota', 'Vestuario alegre'],
    materials: ['Goma eva', 'Cordón artesanal'],
    isFeatured: true,
    availability: 'made-to-order',
    tags: ['muñeca', 'pareja', 'fofucho', 'mascota'],
  },
  {
    id: 'prod-18',
    slug: 'fofucho-motociclista-harley-custom-18',
    name: 'Fofucho Motociclista Harley Custom con Mascota',
    category: 'Muñecas',
    description: 'Impresionante figura personalizada de motociclista con su moto chopper custom a escala y su perrito compañero en el asiento trasero. Incluye chaqueta de cuero símil en goma eva, casco y detalles mecánicos.',
    shortDescription: 'Motociclista personalizado con moto chopper a escala y mascota.',
    image: '/images/img/is18.jpg',
    secondaryImages: ['/images/img/is19.jpg'],
    price: '$65.000',
    priceLabel: '100% personalizado',
    features: ['Moto customizada con rueda ancha', 'Mascota acompañante modelada', 'Chaqueta y casco detallados', 'Base de exhibición incluida'],
    materials: ['Goma eva de alta densidad', 'Pinturas metalizadas', 'Detalles en vinilo'],
    isFeatured: true,
    availability: 'made-to-order',
    tags: ['muñeca', 'moto', 'motociclista', 'fofucho', 'harley', 'mascota'],
  },
  {
    id: 'prod-19',
    slug: 'moto-chopper-escala-19',
    name: 'Moto Chopper Artesanal con Fofucho (Vista Frontal)',
    category: 'Muñecas',
    description: 'Angulo frontal del motociclista mostrando los faros, manubrio de la moto artesanal y gafas de sol espejadas.',
    shortDescription: 'Vista frontal del fofucho motociclista y su moto chopper.',
    image: '/images/img/is19.jpg',
    secondaryImages: ['/images/img/is18.jpg'],
    price: '$65.000',
    priceLabel: 'Set exhibición',
    features: ['Neumático delantero con relieve', 'Manillar azul con palancas', 'Detalles cromados y logos'],
    materials: ['Goma eva termoformada', 'Pintura plateada'],
    availability: 'available',
    tags: ['muñeca', 'moto', 'fofucho', 'escala'],
  },
  {
    id: 'prod-20',
    slug: 'tarjeta-cuadros-cristales-20',
    name: 'Tarjeta Elegante "We\'re All In This Together"',
    category: 'Tarjetas',
    description: 'Diseño exclusivo de tarjeta minimalista en cartulina negra con bordados dorados de mariposas y mensaje de solidaridad.',
    shortDescription: 'Tarjeta negra con grabados dorados y mensaje emotivo.',
    image: '/images/img/is20.jpg',
    secondaryImages: ['/images/img/is7.jpg', '/images/img/is11.jpg'],
    price: '$11.000',
    priceLabel: 'Unidad',
    features: ['Cartulina negra mate', 'Grabado dorado brillante', 'Mensaje inspirador'],
    materials: ['Cartulina de diseño', 'Gemas'],
    availability: 'available',
    tags: ['tarjeta', 'dorado', 'artesanal', 'solidaridad'],
  },
  {
    id: 'prod-21',
    slug: 'tarjeta-happy-fathers-day-21',
    name: 'Tarjeta "Happy Father\'s Day!!"',
    category: 'Tarjetas',
    description: 'Tarjeta desplegable artesanal en tono negro y amarillo con lazo dorado para el Día del Padre.',
    shortDescription: 'Tarjeta sorpresa desplegable con lazo dorado para papá.',
    image: '/images/img/is21.jpg',
    secondaryImages: ['/images/img/is22.jpg'],
    price: '$12.000',
    priceLabel: 'Unidad',
    features: ['Cierre con lazo dorado', 'Tarjeta sorpresa', 'Diseño moderno para papá'],
    materials: ['Cartulina y Cinta Dorada'],
    availability: 'available',
    tags: ['tarjeta', 'dia-del-padre', 'regalo'],
  },
  {
    id: 'prod-22',
    slug: 'tarjeta-acordeon-the-world-is-yours-22',
    name: 'Tarjeta Plegable Acordeón "The World is Yours"',
    category: 'Tarjetas',
    description: 'Tarjeta artesanal con apertura en acordeón de múltiples paneles, con caligrafía vintage estampada, sellos decorativos y mensajes inspiradores.',
    shortDescription: 'Tarjeta artesanal plegable en acordeón con textura vintage.',
    image: '/images/img/is22.jpg',
    secondaryImages: [],
    price: '$14.000',
    priceLabel: 'Unidad con sobre',
    features: ['Estructura plegable en acordeón', 'Fondo vintage texturado con sellos', 'Espacio para dedicatoria personalizada'],
    materials: ['Cartulina de alto gramaje', 'Tintas de archivo', 'Sobre decorado'],
    isFeatured: true,
    availability: 'available',
    tags: ['tarjeta', 'acordeon', 'vintage'],
  },
  {
    id: 'prod-23',
    slug: 'fofucha-doctora-maestra-verde-23',
    name: 'Fofucha Doctora / Maestra Traje Verde',
    category: 'Muñecas',
    description: 'Muñeca fofucha con abundante cabello amarillo brillante luciendo traje profesional verde con estetoscopio o collar artesanal.',
    shortDescription: 'Fofucha profesional con traje verde y peinado llamativo.',
    image: '/images/img/is23.jpg',
    secondaryImages: [],
    price: '$42.000',
    priceLabel: 'Unidad',
    features: ['Cabello rubio exuberante', 'Atuendo profesional verde', 'Tenis deportivos blancos'],
    materials: ['Goma eva', 'Acrílicos'],
    availability: 'available',
    tags: ['muñeca', 'fofucha', 'profesion', 'doctora'],
  },
  {
    id: 'prod-24',
    slug: 'llavero-artesanal-flor-rosa-mariposa-24',
    name: 'Llavero Artesanal Flor Rosa y Mariposa',
    category: 'Papelería',
    description: 'Elegante llavero artesanal con cuentas de vidrio trabajadas, dije de mariposa rosa y flor de tela hecha a mano.',
    shortDescription: 'Llavero de cristal con flor rosa y dije de mariposa.',
    image: '/images/img/is24.jpg',
    secondaryImages: ['/images/img/is25.jpg', '/images/img/is26.jpg'],
    price: '$10.000',
    priceLabel: 'Unidad',
    features: ['Flor de tela hecha a mano', 'Cuentas de bisutería finas', 'Mosquetón metálico'],
    materials: ['Tela, Metal y Cuentas de Vidrio'],
    availability: 'available',
    tags: ['papeleria', 'llavero', 'flor', 'mariposa'],
  },
  {
    id: 'prod-25',
    slug: 'llavero-colgante-flor-mariposa-25',
    name: 'Llavero Colgante Flor Rosa en Bolso',
    category: 'Papelería',
    description: 'Elegante accesorio para bolsos o mochilas, compuesto por flor de tela rosa artesanal, cuentas facetadas de colores y dije de mariposa.',
    shortDescription: 'Llavero artesanal enganchado como accesorio de bolso.',
    image: '/images/img/is25.jpg',
    secondaryImages: ['/images/img/is24.jpg', '/images/img/is26.jpg'],
    price: '$10.000',
    priceLabel: 'Unidad',
    features: ['Flor confeccionada a mano', 'Cuentas con motivos florales', 'Herraje metálico reforzado'],
    materials: ['Goma eva y tela', 'Cuentas acrílicas estampadas', 'Aro de acero'],
    isFeatured: true,
    availability: 'available',
    tags: ['llavero', 'accesorio', 'mariposa', 'flor', 'papeleria'],
  },
  {
    id: 'prod-26',
    slug: 'llavero-cuentas-cristal-azul-26',
    name: 'Llavero Cuentas de Cristal Azul y Flor',
    category: 'Papelería',
    description: 'Llavero artesanal con aro azul turquesa, pequeña flor magenta y cuentas cilindricas con motivos arabescos.',
    shortDescription: 'Llavero artesanal azul turquesa con flor magenta.',
    image: '/images/img/is26.jpg',
    secondaryImages: ['/images/img/is24.jpg', '/images/img/is25.jpg'],
    price: '$9.500',
    priceLabel: 'Unidad',
    features: ['Aro de metal lacado azul', 'Cuentas decorativas arabescas', 'Diseño compacto'],
    materials: ['Metal y Cristal'],
    availability: 'available',
    tags: ['llavero', 'papeleria', 'cristal'],
  },
  {
    id: 'prod-27',
    slug: 'organizador-infantil-selva-reciclado-27',
    name: 'Organizador Infantil Selva Mágica Reciclado',
    category: 'Manualidades Recicladas',
    description: 'Contenedor y organizador para cuarto de juegos o cambiador de bebé, confeccionado con estructura reciclada, forro verde esmeralda y volante exterior con motivos de animalitos de la selva y puntilla tejida verde.',
    shortDescription: 'Organizador infantil reciclado con estampado de selva y puntilla verde.',
    image: '/images/img/is27.jpg',
    secondaryImages: [],
    price: '$24.000',
    priceLabel: 'Unidad',
    features: ['Materiales reutilizados con acabado premium', 'Estampado infantil de animalitos', 'Puntilla decorativa verde', 'Espacioso y resistente'],
    materials: ['Caja reciclada reforzada', 'Telas de algodón', 'Puntilla tejida', 'Goma eva base'],
    isFeatured: true,
    availability: 'available',
    tags: ['reciclado', 'infantil', 'organizador', 'selva', 'sostenible'],
  },
  {
    id: 'prod-28',
    slug: 'muneca-minnie-mouse-abrigo-blanco-28',
    name: 'Muñeca Minnie Mouse con Abrigo Blanco y Bolso',
    category: 'Muñecas',
    description: 'Fofucha personalizada inspirada en Minnie Mouse con orejitas negras, lazo rojo a lunares, suéter blanco y cartera combinada.',
    shortDescription: 'Fofucha estilo Minnie Mouse con lazo rojo y abriguito blanco.',
    image: '/images/img/is28.jpg',
    secondaryImages: [],
    price: '$45.000',
    priceLabel: 'Unidad',
    features: ['Detalles de Minnie Mouse', 'Carterita en miniatura', 'Zapatos blancos modernos'],
    materials: ['Goma eva premium'],
    isFeatured: true,
    availability: 'available',
    tags: ['muñeca', 'minnie', 'fofucha', 'personajes'],
  },
  {
    id: 'prod-29',
    slug: 'topper-lapiz-princesa-violeta-29',
    name: 'Topper de Lápiz Princesa en Vestido Violeta',
    category: 'Papelería',
    description: 'Adorno para lápiz o bolígrafo con figura de princesita rubia con corona dorada y vestido morado sobre base floral.',
    shortDescription: 'Topper artesanal de princesita violeta para lápices.',
    image: '/images/img/is29.jpg',
    secondaryImages: ['/images/img/is32.jpg'],
    price: '$8.500',
    priceLabel: 'Unidad',
    features: ['Encaja en cualquier lápiz estándar', 'Corona con escarcha dorada', 'Muy ligero'],
    materials: ['Goma eva', 'Base plástica'],
    availability: 'available',
    tags: ['papeleria', 'topper', 'lapiz', 'princesa'],
  },
  {
    id: 'prod-30',
    slug: 'muneca-enfermera-embarazada-cna-30',
    name: 'Muñeca Enfermera / CNA Embarazada con Mascarilla',
    category: 'Muñecas',
    description: 'Muñeca personalizada de enfermera médica embarazada luciendo bata colorida, mascarilla de protección y zuecos crocs rosa.',
    shortDescription: 'Fofucha de enfermera embarazada con mascarilla y chapa CNA.',
    image: '/images/img/is30.jpg',
    secondaryImages: ['/images/img/is31.jpg'],
    price: '$46.000',
    priceLabel: 'Personalizada',
    features: ['Representación de enfermera embarazada', 'Crocs rosas en miniatura', 'Chapa CNA en la espalda'],
    materials: ['Goma eva y mascarilla de tela'],
    isFeatured: true,
    availability: 'made-to-order',
    tags: ['muñeca', 'enfermera', 'fofucha', 'profesion'],
  },
  {
    id: 'prod-31',
    slug: 'muneca-enfermera-cna-trasera-31',
    name: 'Muñeca Enfermera CNA - Vista Trasera',
    category: 'Muñecas',
    description: 'Vista posterior de la muñeca enfermera destacando el parche "CNA" moldeado en amarillo y naranja.',
    shortDescription: 'Detalle posterior de fofucha enfermera CNA.',
    image: '/images/img/is31.jpg',
    secondaryImages: ['/images/img/is30.jpg'],
    price: '$44.000',
    priceLabel: 'Unidad',
    features: ['Identificador personalizable', 'Detalle en el abrigo', 'Estructura firme'],
    materials: ['Goma eva'],
    availability: 'available',
    tags: ['muñeca', 'enfermera', 'fofucha'],
  },
  {
    id: 'prod-32',
    slug: 'topper-lapiz-cenicienta-32',
    name: 'Topper de Lápiz Cenicienta con Moño Rubio',
    category: 'Papelería',
    description: 'Topper artesanal para bolígrafo inspirado en Cenicienta con su clásico vestido azul celeste y guantes blancos.',
    shortDescription: 'Topper artesanal para bolígrafo de princesa Cenicienta.',
    image: '/images/img/is32.jpg',
    secondaryImages: ['/images/img/is29.jpg'],
    price: '$8.500',
    priceLabel: 'Unidad',
    features: ['Vestido azul brillante', 'Peinado en moño rubio', 'Fácil de intercambiar'],
    materials: ['Goma eva'],
    availability: 'available',
    tags: ['papeleria', 'topper', 'princesa'],
  },
  {
    id: 'prod-33',
    slug: 'muneca-mama-bebe-caja-regalo-33',
    name: 'Muñeca Mamá Abrazando Bebé en Caja Vitrina',
    category: 'Cajas Decoradas',
    description: 'Emotivo regalo presentado en caja decorada con ventana transparente: muñeca mamá sosteniendo amorosamente a su recién nacido.',
    shortDescription: 'Muñeca mamá y bebé presentada en caja vitrina con moño gigante.',
    image: '/images/img/is33.jpg',
    secondaryImages: ['/images/img/is35.jpg'],
    price: '$48.000',
    priceLabel: 'Caja con muñeca',
    features: ['Presentación lista para regalo', 'Escena tierna de maternidad', 'Moño gigante de regalo'],
    materials: ['Goma eva y Caja de Cartón con Acetato'],
    isFeatured: true,
    availability: 'available',
    tags: ['cajas-regalo', 'muñeca', 'maternidad', 'bebe'],
  },
  {
    id: 'prod-34',
    slug: 'sobre-regalo-bienvenida-bebe-cora-34',
    name: 'Sobres y Cajas de Regalo Personalizadas "Cora"',
    category: 'Cajas Decoradas',
    description: 'Set de envoltorios de regalo rosa pastel decorados con moños elegantes, flores de tela y aplique de bebé con nombre en relieve.',
    shortDescription: 'Set de empaques personalizados para baby shower y recién nacido.',
    image: '/images/img/is34.jpg',
    secondaryImages: [],
    price: '$16.000',
    priceLabel: 'Set de empaque',
    features: ['Sobres acolchados', 'Lazos de organza', 'Personalización con nombre'],
    materials: ['Papel Especial, Goma eva y Cintas'],
    isNew: true,
    isFeatured: true,
    availability: 'available',
    tags: ['cajas-regalo', 'empaque', 'bebe', 'personalizado'],
  },
  {
    id: 'prod-35',
    slug: 'muneca-mama-bebe-detalle-35',
    name: 'Muñeca Mamá Abrazando Bebé (Detalle de Rostro)',
    category: 'Muñecas',
    description: 'Acercamiento a la cara expresiva de la mamá y el bebito en brazos con mantita amarilla.',
    shortDescription: 'Detalle de la escena de ternura entre mamá y bebé.',
    image: '/images/img/is35.jpg',
    secondaryImages: ['/images/img/is33.jpg'],
    price: '$42.000',
    priceLabel: 'Unidad',
    features: ['Expresión tierna y emotiva', 'Pintura facial con matices', 'Ideal para día de la madre'],
    materials: ['Goma eva'],
    availability: 'available',
    tags: ['muñeca', 'maternidad', 'madre'],
  },
  {
    id: 'prod-36',
    slug: 'muneca-repostera-cupcakes-36',
    name: 'Muñeca Repostera con Cupcakes y Gafas',
    category: 'Muñecas',
    description: 'Simpática fofucha repostera con montura de gafas rosa luciendo vestido estampado y sosteniendo deliciosos cupcakes artesanales.',
    shortDescription: 'Fofucha pastelera con cupcakes detallados y gafas rosa.',
    image: '/images/img/is36.jpg',
    secondaryImages: ['/images/img/is37.jpg'],
    price: '$45.000',
    priceLabel: 'Unidad artesanal',
    features: ['Cupcakes miniatura detallados', 'Gafas de alambre rosa', 'Peinado recogido con flores'],
    materials: ['Goma eva y accesorios'],
    isFeatured: true,
    availability: 'available',
    tags: ['muñeca', 'fofucha', 'repostera', 'cocina'],
  },
  {
    id: 'prod-37',
    slug: 'muneca-repostera-peinado-37',
    name: 'Muñeca Repostera - Detalle del Peinado',
    category: 'Muñecas',
    description: 'Toma superior del peinado castaño aderezado con pequeñas florecillas de colores hechas a mano.',
    shortDescription: 'Detalle del peinado con flores en fofucha repostera.',
    image: '/images/img/is37.jpg',
    secondaryImages: ['/images/img/is36.jpg'],
    price: '$40.000',
    priceLabel: 'Unidad',
    features: ['Flores artesanales en cabello', 'Textura de peinado', 'Vista detallada superior'],
    materials: ['Goma eva'],
    availability: 'available',
    tags: ['muñeca', 'fofucha', 'repostera'],
  },
  {
    id: 'prod-38',
    slug: 'set-bolsa-tarjeta-dragon-fuego-38',
    name: 'Tarjeta y Bolsa de Regalo Dragón Rojo 3D',
    category: 'Cajas Decoradas',
    description: 'Set de empaque temático con bolsa kraft decorada con silueta de dragón rojo escarchado en 3D acompañado de tarjeta de cumpleaños escrita a mano.',
    shortDescription: 'Bolsa kraft y tarjeta con dragón rojo escarchado en relieve 3D.',
    image: '/images/img/is38.jpg',
    secondaryImages: [],
    price: '$18.000',
    priceLabel: 'Set bolsa + tarjeta',
    features: ['Dragón en foami escarchado', 'Bolsa artesanal con asa de yute', 'Tarjeta temática incluida'],
    materials: ['Papel Kraft, Goma eva Glitter y Yute'],
    isFeatured: true,
    availability: 'available',
    tags: ['cajas-regalo', 'empaque', 'dragon', 'tarjeta'],
  },
  {
    id: 'prod-39',
    slug: 'topper-boligrafo-dama-unstoppable-39',
    name: 'Topper de Bolígrafo Dama Elegante "Unstoppable"',
    category: 'Papelería',
    description: 'Topper exclusivo para lápiz de busto de dama con pamela negra decorada con perlas, encaje y cartel "Unstoppable".',
    shortDescription: 'Topper chic para lápiz con sombrero de ala ancha y cartel motivacional.',
    image: '/images/img/is39.jpg',
    secondaryImages: [],
    price: '$9.000',
    priceLabel: 'Unidad',
    features: ['Pamela de ala ancha con velo', 'Placa de mensaje motivacional', 'Diseño muy chic'],
    materials: ['Goma eva, Perlas y Encaje'],
    availability: 'available',
    tags: ['papeleria', 'topper', 'elegante'],
  },
  {
    id: 'prod-40',
    slug: 'mueble-organizador-bano-reciclado-40',
    name: 'Organizador de Baño Reciclado con Flores',
    category: 'Manualidades Recicladas',
    description: 'Mueble auxiliar organizador rústico fabricado con materiales reciclados para colocar papel higiénico, toallas y jarroncito decorativo.',
    shortDescription: 'Organizador de baño rústico ecológico con florero decorativo.',
    image: '/images/img/is40.jpg',
    secondaryImages: [],
    price: '$35.000',
    priceLabel: 'Unidad',
    features: ['Estructura ecológica', 'Acabado rústico vintage', 'Incluye florero de cuerda'],
    materials: ['Madera Reciclada, Cartón y Cuerda'],
    availability: 'available',
    tags: ['reciclado', 'organizador', 'bano', 'hogar'],
  },
  {
    id: 'prod-41',
    slug: 'trio-fofuchas-chicas-superpoderosas-41',
    name: 'Trío Fofuchas Chicas Superpoderosas',
    category: 'Muñecas',
    description: 'Conjunto completo de 3 muñequitas fofuchas representando a Bombón, Burbuja y Bellota con sus vestidos icónicos y grandiosos ojos.',
    shortDescription: 'Set completo de 3 fofuchas inspiradas en las Chicas Superpoderosas.',
    image: '/images/img/is41.jpg',
    secondaryImages: [],
    price: '$52.000',
    priceLabel: 'Set x3 muñecas',
    features: ['Set completo de 3 personajes', 'Ojos expresivos pintados a mano', 'Bases individuales'],
    materials: ['Goma eva de colores vivos'],
    isFeatured: true,
    availability: 'available',
    tags: ['muñeca', 'fofucha', 'personajes', 'superpoderosas'],
  },
  {
    id: 'prod-42',
    slug: 'puntera-lapiz-pollito-corazon-42',
    name: 'Topper de Lápiz Pollito Amarillo Kawaii',
    category: 'Papelería',
    description: 'Tierno topper para lápiz de cabecita de pollito amarillo con ojos kawaii enormes y alitas en forma de corazón.',
    shortDescription: 'Topper kawaii de pollito amarillo con alas de corazón.',
    image: '/images/img/is42.jpg',
    secondaryImages: [],
    price: '$7.500',
    priceLabel: 'Unidad',
    features: ['Estilo Kawaii entrañable', 'Muy liviano', 'Ideal para niños'],
    materials: ['Goma eva soft'],
    availability: 'available',
    tags: ['papeleria', 'topper', 'lapiz', 'pollito'],
  },
  {
    id: 'prod-43',
    slug: 'organizador-reciclado-cascanueces-43',
    name: 'Organizador Reciclado Cascanueces Navideño',
    category: 'Manualidades Recicladas',
    description: 'Figura de soldado cascanueces elaborado a partir de un tubo reciclado decorado con foami escarchado y galones dorados.',
    shortDescription: 'Contenedor navideño de cascanueces elaborado con tubo reciclado.',
    image: '/images/img/is43.jpg',
    secondaryImages: ['/images/img/is44.jpg'],
    price: '$28.000',
    priceLabel: 'Edición Navideña',
    features: ['Contenedor funcional interior', 'Diseño tradicional de cascanueces', 'Adorno navideño único'],
    materials: ['Tubo de Cartón Reciclado y Foami Glitter'],
    isSeasonal: true,
    availability: 'available',
    tags: ['reciclado', 'navidad', 'cascanueces', 'organizador'],
  },
  {
    id: 'prod-44',
    slug: 'set-decorativo-navideno-santa-nieve-44',
    name: 'Set Decorativo Navideño Papá Noel y Muñeco de Nieve',
    category: 'Manualidades Recicladas',
    description: 'Set de adornos navideños con telas recicladas que incluye Papá Noel sentado con barbita de lana y tubo de muñeco de nieve.',
    shortDescription: 'Adornos navideños artesanales de Papá Noel y muñeco de nieve.',
    image: '/images/img/is44.jpg',
    secondaryImages: ['/images/img/is43.jpg', '/images/img/is45.jpg'],
    price: '$32.000',
    priceLabel: 'Edición Navideña',
    features: ['Especial decoración navideña', 'Detalles en lana y fieltro', 'Cálido diseño festivo'],
    materials: ['Telas, Cartón Reciclado y Lana'],
    isSeasonal: true,
    availability: 'available',
    tags: ['reciclado', 'navidad', 'santa', 'nieve'],
  },
  {
    id: 'prod-45',
    slug: 'calcetin-navideno-arpillera-reciclado-45',
    name: 'Calcetín Navideño Reciclado y Cojín Decorativo',
    category: 'Manualidades Recicladas',
    description: 'Bota navideña para chimenea en tela de arpillera/yute adornada con piñas secas y follaje de pino natural.',
    shortDescription: 'Bota navideña rústica de yute con piñas de pino.',
    image: '/images/img/is45.jpg',
    secondaryImages: ['/images/img/is48.jpg'],
    price: '$25.000',
    priceLabel: 'Edición Navideña',
    features: ['Estilo rústico navideño', 'Arpillera eco-friendly', 'Listo para colgar'],
    materials: ['Yute, Piñas de Pino y Fieltro'],
    isSeasonal: true,
    availability: 'available',
    tags: ['reciclado', 'navidad', 'calcetin', 'yute'],
  },
  {
    id: 'prod-46',
    slug: 'muneco-papa-noel-sentado-46',
    name: 'Muñeco Papá Noel Sentado',
    category: 'Muñecas',
    description: 'Figura articulada de Papá Noel pensada para sentar en estanterías o repisas con gorro rojo flojo y medias a rayas.',
    shortDescription: 'Muñeco artesanal de Papá Noel sentado con piernas flexibles.',
    image: '/images/img/is46.jpg',
    secondaryImages: ['/images/img/is47.jpg'],
    price: '$38.000',
    priceLabel: 'Edición Navideña',
    features: ['Patas colgantes flexibles', 'Barba de fibra peluche', 'Adorno festivo'],
    materials: ['Tela, Algodón y Fieltro'],
    isSeasonal: true,
    availability: 'available',
    tags: ['muñeca', 'navidad', 'papa-noel'],
  },
  {
    id: 'prod-47',
    slug: 'muneco-papa-noel-poinsettia-47',
    name: 'Muñeco Papá Noel - Detalle con Flor de Pascua',
    category: 'Muñecas',
    description: 'Acercamiento al cuerpo del muñeco Papá Noel luciendo su chaleco de cuadros y flor poinsettia entre sus manos.',
    shortDescription: 'Detalle de Papá Noel artesanal con flor nochebuena.',
    image: '/images/img/is47.jpg',
    secondaryImages: ['/images/img/is46.jpg'],
    price: '$36.000',
    priceLabel: 'Edición Navideña',
    features: ['Detalle en flor navideña', 'Acabado suave', 'Estructura adaptable'],
    materials: ['Tela y Fieltro'],
    isSeasonal: true,
    availability: 'available',
    tags: ['muñeca', 'navidad', 'papa-noel'],
  },
  {
    id: 'prod-48',
    slug: 'adorno-colgante-campanas-yute-48',
    name: 'Adorno Colgante Campanas Navideñas de Yute',
    category: 'Manualidades Recicladas',
    description: 'Adorno triple colgante para puerta en forma de campanas confeccionadas en arpillera con cordones y flores navideñas rojas.',
    shortDescription: 'Adorno triple de campanas de yute para puerta.',
    image: '/images/img/is48.jpg',
    secondaryImages: ['/images/img/is45.jpg'],
    price: '$24.000',
    priceLabel: 'Edición Navideña',
    features: ['Tres niveles colgantes', 'Decora puertas principales', 'Confección artesanal'],
    materials: ['Yute, Cordel y Flores de Tela'],
    isSeasonal: true,
    availability: 'available',
    tags: ['reciclado', 'navidad', 'campanas', 'yute'],
  }
];

export function getProductsByCategory(category: string): Product[] {
  if (category === 'Todos') return products;
  return products.filter(p => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.isFeatured);
}

export function getNewProducts(): Product[] {
  return products.filter(p => p.isNew);
}

export function getSeasonalProducts(): Product[] {
  return products.filter(p => p.isSeasonal);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter(p => p.id !== product.id && (p.category === product.category || (p.tags && product.tags && p.tags.some(tag => product.tags.includes(tag)))))
    .slice(0, limit);
}